---
title: "pre_heatmap_v1"
output: html_document
date: "2023-01-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Command + option + I でRチャンク挿入

# load data
```{r}
library(tidyverse)
df1 <- readRDS("/Users/saeko/Documents/MOCCS/important_chipseq_prediction/TF_CT_sample_num.rds")
anno_df <- readRDS("/Users/saeko/Documents/MOCCS/important_chipseq_prediction/annotation_df2.rds")
df1
anno_df
```

```{r}
summary(anno_df)
head(anno_df)
dim(anno_df)
```

```{r}
TF_name <- df1$Antigen
df2 <- df1 %>% ungroup() %>% select(-Antigen) 
rownames(df2) <- TF_name
df3 <- as.numeric(unlist(df2))

n<-ncol(df2)
ix<-1:n
df3 <-sapply(df2[ix],as.numeric)
rownames(df3) <- TF_name
dim(df3)

#library(gplots)
#heatmap.2(df3,trace="none")

# devtools::install_version("rjson", "0.2.15")
library(ComplexHeatmap)
# heatmap(df3) #row_order = xx, column_order = xx でクラスタリングなしでできる -> Cell typeをCell type classごとにならび変えて、クラスタリングなしでやってみる？

library(circlize)
col_fun = colorRamp2(c(-3, 0, 3), c("gray", "white", "red"))
Heatmap(df3, col = col_fun, cluster_rows = TRUE, cluster_columns = TRUE, row_names_gp = gpar(fontsize = 0.5), column_names_gp = gpar(fontsize = 0.5))
```

# Cell type class ごとにheatmap 
```{r}
# Cell type classのアノテーションをふる top_annotation = HeatmapAnnotation(foo1 = 1:24, bar1 = anno_points(runif(24))) とか？

heatmap(df3) #row_order = xx, column_order = xx でクラスタリングなしでできる -> Cell typeをCell type classごとにならび変えて、クラスタリングなしでやってみる？
Heatmap(df3, )
```
# ここはもうやらなくても大丈夫なセル！！
```{r}
# Cell type classごとに列名を変更する (列を20列に変更する)
df4 <- anno_df %>% group_by(Cell_type_class, Antigen) %>% summarize(num = n())
df4

df5 <- df4 %>% pivot_wider(names_from = Cell_type_class, values_from = num)
row_lab <- df5$Antigen
df6 <- df5 %>% select(-Antigen)
df7 <- df6 %>% as.matrix()
rownames(df7) <- row_lab
df7[which(is.na(df7))] <- 0
head(df7)
dim(df7)
saveRDS(df7, "/Users/saeko/Documents/MOCCS/important_chipseq_prediction/TF_CTC_sample_num.rds")
```


```{r}
df7 <- readRDS("/Users/saeko/Documents/MOCCS/important_chipseq_prediction/TF_CTC_sample_num.rds")
head(df7)
dim(df7)
summary(df7)

library(ComplexHeatmap)
heatmap(df7)
for(i in 1:20){
  hist(df7[,i],breaks = 30)
}

```
# ComplexHeatmap
https://jokergoo.github.io/ComplexHeatmap-reference/book/index.html

```{r}
# rowごとにsample数集計
row_sum <- apply(df7, 1, sum)
# colごとにsample数集計
col_sum <- apply(df7, 2, sum)

library(circlize)
col_fun = colorRamp2(c(-10, 0, 10), c("gray", "white", "red"))
Heatmap(df7, col = col_fun, cluster_rows = FALSE, cluster_columns = FALSE, top_annotation = HeatmapAnnotation(sample_sum = anno_barplot(col_sum)), row_names_gp = gpar(fontsize = 0), column_names_gp = gpar(fontsize = 8))
```

# TF family × Cell type class
```{r}
# TF family のアノテーションをふる left_annotation = rowAnnotation(foo2 = 18:1, bar2 = anno_barplot(runif(18))) とか？
TF_fam <- read_tsv("/Users/saeko/MOCCS_paper_public/data/Fig3/TF_Information.txt")
head(TF_fam)

# join
Antigen_anno <- anno_df$Antigen %>% as.character() %>% unique()
Antigen_TF_fam <- TF_fam$TF_Name %>% as.character() %>% unique()
Antigen_share <- intersect(Antigen_anno, Antigen_TF_fam)
length(Antigen_share)
TF_fam2 <- TF_fam %>% filter(TF_Name %in% Antigen_share) %>% select(TF_Name, Family_Name)
colnames(TF_fam2) <- c("Antigen", "Antigen_family")
anno_df_fam <- anno_df %>% left_join(TF_fam2, by = "Antigen")
saveRDS(anno_df_fam, "/Users/saeko/Documents/MOCCS/important_chipseq_prediction/annotation_family.rds")
```


# ここはもうやらなくて良いセル！！
```{r}
# TF familyごとに行名を変更する (行を少なめに変更する)
anno_df_fam <- readRDS("/Users/saeko/Documents/MOCCS/important_chipseq_prediction/annotation_family.rds")
TF_family <- anno_df_fam$Antigen_family %>% as.character() %>% unique()
length(TF_family)

# TF family ごとに行名を変更する (列を20列に変更する)
df8 <- anno_df_fam %>% drop_na(Antigen_family) %>% group_by(Cell_type_class, Antigen_family) %>% summarize(num = n())
df8

df9 <- df8 %>% pivot_wider(names_from = Cell_type_class, values_from = num)
row_lab <- df9$Antigen_family
df10 <- df9 %>% select(-Antigen_family)
df11 <- df10 %>% as.matrix()
rownames(df11) <- row_lab
df11[which(is.na(df11))] <- 0
head(df11)
dim(df11)
saveRDS(df11, "/Users/saeko/Documents/MOCCS/important_chipseq_prediction/TF_family_CTC_sample_num.rds")
```

```{r}
df11 <- readRDS("/Users/saeko/Documents/MOCCS/important_chipseq_prediction/TF_family_CTC_sample_num.rds")
df12 <- t(df11)
head(df12)
dim(df12)

# rowごとにsample数集計
row_sum <- apply(df12, 1, sum)
summary(row_sum)
# colごとにsample数集計
col_sum <- apply(df12, 2, sum)
summary(col_sum)

library(circlize)
col_fun = colorRamp2(c(0,5000), c( "white", "red"))
Heatmap(df12, col = col_fun, cluster_rows = TRUE, cluster_columns = TRUE, top_annotation = HeatmapAnnotation(sample = anno_barplot(col_sum)), right_annotation = rowAnnotation(sample = anno_barplot(row_sum)), row_names_gp = gpar(fontsize = 8), column_names_gp = gpar(fontsize = 6))

```
# マウス、TF ChIP-seq
```{r}
df <- readRDS("/Users/saeko/Documents/MOCCS/paper_figure/MOCCS_paper_public/analysis/DROMPA_hg38/data/experimentList_tab4.rds")
anno_df <- df %>% filter(Genome == "mm9" & Antigen_class == "TFs and others") 
dim(anno_df)
length(unique(anno_df$ID))
unique(anno_df$Antigen)
length(unique(anno_df$Antigen))
length(unique(anno_df$Cell_type_class))
```

```{r}
df4 <- anno_df %>% group_by(Cell_type_class, Antigen) %>% summarize(num = n())
df4

df5 <- df4 %>% pivot_wider(names_from = Cell_type_class, values_from = num)
row_lab <- df5$Antigen
df6 <- df5 %>% select(-Antigen)
df7 <- df6 %>% as.matrix()
rownames(df7) <- row_lab
df7[which(is.na(df7))] <- 0
head(df7)
dim(df7)
saveRDS(df7, "/Users/saeko/Documents/MOCCS/important_chipseq_prediction/mm9_TF_CTC_sample_num.rds")
```

```{r}
df7 <- readRDS("/Users/saeko/Documents/MOCCS/important_chipseq_prediction/mm9_TF_CTC_sample_num.rds")
head(df7)
dim(df7)
summary(df7)
```
# ComplexHeatmap
https://jokergoo.github.io/ComplexHeatmap-reference/book/index.html

```{r}
df7 <- t(df7)
# rowごとにsample数集計
row_sum <- apply(df7, 1, sum)
# colごとにsample数集計
col_sum <- apply(df7, 2, sum)

library(circlize)
col_fun = colorRamp2(c(-10, 0, 10), c("gray", "white", "red"))
Heatmap(df7, col = col_fun, cluster_rows = FALSE, cluster_columns = FALSE, top_annotation = HeatmapAnnotation(sample_sum = anno_barplot(col_sum)), right_annotation = rowAnnotation(sample = anno_barplot(row_sum)),row_names_gp = gpar(fontsize = 6), column_names_gp = gpar(fontsize = 0))

#クラスタリングあり
Heatmap(df7, col = col_fun, cluster_rows = TRUE, cluster_columns = TRUE, top_annotation = HeatmapAnnotation(sample_sum = anno_barplot(col_sum)), right_annotation = rowAnnotation(sample = anno_barplot(row_sum)),row_names_gp = gpar(fontsize = 6), column_names_gp = gpar(fontsize = 0))
```
# マウス、Histone
```{r}
df <- readRDS("/Users/saeko/Documents/MOCCS/paper_figure/MOCCS_paper_public/analysis/DROMPA_hg38/data/experimentList_tab4.rds")
anno_df <- df %>% filter(Genome == "mm9" & Antigen_class == "Histone") 
dim(anno_df)
length(unique(anno_df$ID))
unique(anno_df$Antigen)
length(unique(anno_df$Antigen))
length(unique(anno_df$Cell_type_class))
```

```{r}
df4 <- anno_df %>% group_by(Cell_type_class, Antigen) %>% summarize(num = n())
df4

df5 <- df4 %>% pivot_wider(names_from = Cell_type_class, values_from = num)
row_lab <- df5$Antigen
df6 <- df5 %>% select(-Antigen)
df7 <- df6 %>% as.matrix()
rownames(df7) <- row_lab
df7[which(is.na(df7))] <- 0
head(df7)
dim(df7)
saveRDS(df7, "/Users/saeko/Documents/MOCCS/important_chipseq_prediction/mm9_Histone_TF_CTC_sample_num.rds")
```

```{r}
df7 <- readRDS("/Users/saeko/Documents/MOCCS/important_chipseq_prediction/mm9_TF_CTC_sample_num.rds")
head(df7)
dim(df7)
summary(df7)
```
# ComplexHeatmap
https://jokergoo.github.io/ComplexHeatmap-reference/book/index.html

```{r}
df7 <- t(df7)
# rowごとにsample数集計
row_sum <- apply(df7, 1, sum)
# colごとにsample数集計
col_sum <- apply(df7, 2, sum)

library(circlize)
col_fun = colorRamp2(c(-10, 0, 10), c("gray", "white", "red"))
Heatmap(df7, col = col_fun, cluster_rows = FALSE, cluster_columns = FALSE, top_annotation = HeatmapAnnotation(sample_sum = anno_barplot(col_sum)), right_annotation = rowAnnotation(sample = anno_barplot(row_sum)),row_names_gp = gpar(fontsize = 6), column_names_gp = gpar(fontsize = 3))

#クラスタリングあり
Heatmap(df7, col = col_fun, cluster_rows = TRUE, cluster_columns = TRUE, top_annotation = HeatmapAnnotation(sample_sum = anno_barplot(col_sum)), right_annotation = rowAnnotation(sample = anno_barplot(row_sum)),row_names_gp = gpar(fontsize = 6), column_names_gp = gpar(fontsize = 3))
```
```{r}
```

```{r}
```